// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHoWmIVyHPl3xR_KXKqOK0bjjvqRZHH40',
    appId: '1:367158650760:web:0e87e7c067617b41cbfc3d',
    messagingSenderId: '367158650760',
    projectId: 'gosmart-fd8f6',
    authDomain: 'gosmart-fd8f6.firebaseapp.com',
    storageBucket: 'gosmart-fd8f6.firebasestorage.app',
    measurementId: 'G-RZJ83M067N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiwvUnlg_flBUVxWoRXZmd2o1yQsmLm8Y',
    appId: '1:367158650760:android:98d90f44e01c1896cbfc3d',
    messagingSenderId: '367158650760',
    projectId: 'gosmart-fd8f6',
    storageBucket: 'gosmart-fd8f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm53BUi08mjQdQDLVPm_CybOPguysauvM',
    appId: '1:367158650760:ios:89050f1838df9acfcbfc3d',
    messagingSenderId: '367158650760',
    projectId: 'gosmart-fd8f6',
    storageBucket: 'gosmart-fd8f6.firebasestorage.app',
    iosBundleId: 'com.example.gosmartMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm53BUi08mjQdQDLVPm_CybOPguysauvM',
    appId: '1:367158650760:ios:89050f1838df9acfcbfc3d',
    messagingSenderId: '367158650760',
    projectId: 'gosmart-fd8f6',
    storageBucket: 'gosmart-fd8f6.firebasestorage.app',
    iosBundleId: 'com.example.gosmartMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHoWmIVyHPl3xR_KXKqOK0bjjvqRZHH40',
    appId: '1:367158650760:web:1d366ddbb69be3d3cbfc3d',
    messagingSenderId: '367158650760',
    projectId: 'gosmart-fd8f6',
    authDomain: 'gosmart-fd8f6.firebaseapp.com',
    storageBucket: 'gosmart-fd8f6.firebasestorage.app',
    measurementId: 'G-V2P1RY5QCX',
  );
}
