import 'package:flutter/material.dart';
import '../../domain/ride/canonical_ride.dart';

class CanonicalRideCard extends StatelessWidget {
  const CanonicalRideCard({super.key, required this.ride, required this.driver, required this.loading, this.onPrimary, this.onCancel, this.onDismiss});
  final CanonicalRide ride; final bool driver; final bool loading; final VoidCallback? onPrimary; final VoidCallback? onCancel; final VoidCallback? onDismiss;
  String get statusText => driver ? switch (ride.status) { RideStatus.driverEnRoute => 'Yolcunun konumuna gidiliyor', RideStatus.driverArrived => 'Yolcu bekleniyor', RideStatus.inProgress => 'Yolculuk devam ediyor', RideStatus.completed => 'Yolculuk tamamlandı', RideStatus.cancelled => 'Yolculuk iptal edildi', RideStatus.expired => 'Yolculuk süresi doldu', RideStatus.matching => 'Yolculuk hazırlanıyor' } : switch (ride.status) { RideStatus.matching => 'Sürücü aranıyor', RideStatus.driverEnRoute => 'Sürücü teslim alma noktasına geliyor', RideStatus.driverArrived => 'Sürücü teslim alma noktasına ulaştı', RideStatus.inProgress => 'Yolculuk devam ediyor', RideStatus.completed => 'Yolculuk tamamlandı', RideStatus.cancelled => 'Yolculuk iptal edildi', RideStatus.expired => 'Sürücü bulunamadı' };
  String? get primaryLabel => !driver ? null : switch (ride.status) { RideStatus.driverEnRoute => 'Teslim Alma Noktasına Ulaştım', RideStatus.driverArrived => 'Yolculuğu Başlat', RideStatus.inProgress => 'Yolculuğu Tamamla', _ => null };
  @override Widget build(BuildContext context) => Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Text(statusText, style: Theme.of(context).textTheme.titleMedium), const SizedBox(height: 8), Text('${ride.pickup.addressLabel} → ${ride.dropoff.addressLabel}'), if (primaryLabel != null) ...[const SizedBox(height: 12), FilledButton(onPressed: loading ? null : onPrimary, child: Text(primaryLabel!))], if (onCancel != null) TextButton(onPressed: loading ? null : onCancel, child: const Text('Yolculuğu İptal Et')), if (ride.status.isTerminal && onDismiss != null) TextButton(onPressed: onDismiss, child: const Text('Yeni Yolculuk'))])));
}
