import 'dart:async';
import 'package:flutter_test/flutter_test.dart';
import 'package:gosmart_mobile/application/ride/ride_gateway.dart';
import 'package:gosmart_mobile/controllers/driver_ride_controller.dart';
import 'package:gosmart_mobile/controllers/passenger_ride_controller.dart';
import 'package:gosmart_mobile/domain/ride/canonical_ride.dart';

void main() {
  test('passenger no-active ve active recovery yapar', () async { final fake = FakeRideApi(); final controller = PassengerRideController(gateway: fake, repository: fake); await controller.recover(); expect(controller.ride, isNull); fake.passengerRide = ride(); await controller.recover(); expect(controller.ride?.rideId, 'ride-1'); controller.dispose(); });
  test('create duplicate tap bloklanır ve requestId retry boyunca korunur', () async { final fake = FakeRideApi()..holdCreate = true; final controller = PassengerRideController(gateway: fake, repository: fake, requestIdGenerator: () => 'stable-request'); final first = controller.create(pickup: location, dropoff: location); await controller.create(pickup: location, dropoff: location); expect(fake.createIds, ['stable-request']); fake.createCompleter!.completeError(const RideGatewayException('unavailable')); await first; await controller.create(pickup: location, dropoff: location); expect(fake.createIds, everyElement('stable-request')); controller.dispose(); });
  test('already-exists create active ride recovery yapar', () async { final fake = FakeRideApi()..createError = const RideGatewayException('already-exists')..passengerRide = ride(); final controller = PassengerRideController(gateway: fake, repository: fake); await controller.create(pickup: location, dropoff: location); expect(controller.ride?.rideId, 'ride-1'); controller.dispose(); });
  test('stream ilerler stale snapshot yok sayılır', () async { final fake = FakeRideApi()..passengerRide = ride(version: 2); final controller = PassengerRideController(gateway: fake, repository: fake); await controller.recover(); fake.stream.add(ride(version: 3, status: RideStatus.driverEnRoute)); await Future<void>.delayed(Duration.zero); fake.stream.add(ride(version: 2)); await Future<void>.delayed(Duration.zero); expect(controller.ride?.version, 3); controller.dispose(); });
  test('passenger cancel yalnız izinli statülerde exact actor kullanır', () async { final fake = FakeRideApi()..passengerRide = ride(status: RideStatus.matching); final controller = PassengerRideController(gateway: fake, repository: fake, requestIdGenerator: () => 'cancel-id'); await controller.recover(); await controller.cancel(); expect(fake.cancelDriver, isFalse); expect(fake.cancelVersion, 1); fake.passengerRide = ride(status: RideStatus.inProgress); await controller.recover(); await controller.cancel(); expect(fake.cancelCalls, 1); controller.dispose(); });
  test('stale cancel refresh yapar ve kör mutation retry etmez', () async { final fake = FakeRideApi(); fake.passengerRide = ride(); fake.cancelError = const RideGatewayException('failed-precondition', reason: 'stale_ride_version'); fake.getValue = ride(version: 2, status: RideStatus.driverEnRoute); final controller = PassengerRideController(gateway: fake, repository: fake); await controller.recover(); await controller.cancel(); expect(fake.cancelCalls, 1); expect(controller.ride?.version, 2); controller.dispose(); });
  test('driver recovery ve doğru lifecycle actionları', () async { final fake = FakeRideApi()..driverRide = ride(status: RideStatus.driverEnRoute); final controller = DriverRideController(gateway: fake, repository: fake, requestIdGenerator: () => 'driver-id'); await controller.recover(); await controller.act(DriverRideAction.arrive); expect(fake.arriveCalls, 1); fake.stream.add(ride(version: 2, status: RideStatus.driverArrived)); await Future<void>.delayed(Duration.zero); await controller.act(DriverRideAction.start); expect(fake.startCalls, 1); fake.stream.add(ride(version: 3, status: RideStatus.inProgress)); await Future<void>.delayed(Duration.zero); await controller.act(DriverRideAction.complete); expect(fake.completeCalls, 1); controller.dispose(); });
  test('driver cancel pre-start ile sınırlı ve driver reason kullanır', () async { final fake = FakeRideApi()..driverRide = ride(status: RideStatus.driverArrived); final controller = DriverRideController(gateway: fake, repository: fake); await controller.recover(); await controller.act(DriverRideAction.cancel); expect(fake.cancelDriver, isTrue); fake.stream.add(ride(version: 2, status: RideStatus.inProgress)); await Future<void>.delayed(Duration.zero); await controller.act(DriverRideAction.cancel); expect(fake.cancelCalls, 1); controller.dispose(); });
}

const location = RideLocation(latitude: 41, longitude: 29, addressLabel: 'Adres');
CanonicalRide ride({int version = 1, RideStatus status = RideStatus.matching}) => CanonicalRide(rideId: 'ride-1', status: status, version: version, pickup: location, dropoff: location, route: const RideRoute(distanceMeters: 1, durationSeconds: 1, encodedPolyline: 'x'));

class FakeRideApi implements RideGateway, RideStreamRepository {
  CanonicalRide? passengerRide, driverRide, getValue; RideGatewayException? createError, cancelError; bool holdCreate = false; Completer<CanonicalRide>? createCompleter; final createIds = <String>[]; final stream = StreamController<CanonicalRide>.broadcast(); int cancelCalls = 0, arriveCalls = 0, startCalls = 0, completeCalls = 0; bool? cancelDriver; int? cancelVersion;
  @override Future<CanonicalRide?> getMyActiveRide() async => passengerRide;
  @override Future<CanonicalRide?> getMyActiveDriverRide() async => driverRide;
  @override Future<CanonicalRide> createRide({required String requestId, required RideLocation pickup, required RideLocation dropoff}) { createIds.add(requestId); if (createError case final error?) return Future.error(error); if (holdCreate) { createCompleter = Completer<CanonicalRide>(); holdCreate = false; return createCompleter!.future; } return Future.value(ride()); }
  @override Future<void> cancel({required String rideId, required String requestId, required int expectedVersion, required bool driver}) async { cancelCalls++; cancelDriver = driver; cancelVersion = expectedVersion; if (cancelError case final error?) throw error; }
  @override Future<void> markDriverArrived({required String rideId, required String requestId, required int expectedVersion}) async { arriveCalls++; }
  @override Future<void> startRide({required String rideId, required String requestId, required int expectedVersion}) async { startCalls++; }
  @override Future<void> completeRide({required String rideId, required String requestId, required int expectedVersion}) async { completeCalls++; }
  @override Stream<CanonicalRide> watchRide(String rideId) => stream.stream;
  @override Future<CanonicalRide> getRide(String rideId) async => getValue ?? ride();
}
