import 'dart:async';
import 'package:flutter_test/flutter_test.dart';
import 'package:gosmart_mobile/application/ride/ride_gateway.dart';
import 'package:gosmart_mobile/controllers/driver_ride_controller.dart';
import 'package:gosmart_mobile/controllers/passenger_ride_controller.dart';
import 'package:gosmart_mobile/domain/ride/canonical_ride.dart';

void main() {
  test('signed-out passenger create ve cancel callable üretmez', () async { String? uid; final api=Api()..passenger=ride('one'); final controller=PassengerRideController(gateway:api,repository:api,authenticatedUserId:()=>uid); expect(await controller.create(pickup:point,dropoff:point),isFalse); await controller.recover(); await controller.cancel(); expect(api.createIds,isEmpty); expect(api.cancelIds,isEmpty); controller.dispose(); });
  test('passenger logout listener state ve pending requesti temizler', () async { String? uid='u1'; final api=Api()..passenger=ride('one'); final controller=PassengerRideController(gateway:api,repository:api,authenticatedUserId:()=>uid); await controller.recover(); uid=null; await controller.authChanged(null); expect(controller.ride,isNull); expect(api.cancelled('one'),isTrue); controller.dispose(); });
  test('passenger user değişimi eski listenerı kapatıp recovery yapar', () async { String? uid='u1'; final api=Api()..passenger=ride('one'); final controller=PassengerRideController(gateway:api,repository:api,authenticatedUserId:()=>uid); await controller.recover(); uid='u2'; api.passenger=ride('two'); await controller.authChanged(uid); expect(controller.ride?.rideId,'two'); expect(api.cancelled('one'),isTrue); api.emit('one',ride('one',version:99)); await Future<void>.delayed(Duration.zero); expect(controller.ride?.rideId,'two'); controller.dispose(); expect(api.cancelled('two'),isTrue); });
  test('driver logout ve user değişimi listener ownership korur', () async { String? uid='d1'; final api=Api()..driver=ride('one',status:RideStatus.driverEnRoute); final controller=DriverRideController(gateway:api,repository:api,authenticatedUserId:()=>uid); await controller.recover(); uid='d2'; api.driver=ride('two',status:RideStatus.driverArrived); await controller.authChanged(uid); expect(controller.ride?.rideId,'two'); expect(api.cancelled('one'),isTrue); uid=null; await controller.authChanged(null); expect(controller.ride,isNull); expect(api.cancelled('two'),isTrue); controller.dispose(); });
  test('düşük version snapshot yüksek versionı ezmez', () async { final api=Api()..passenger=ride('one',version:3); final controller=PassengerRideController(gateway:api,repository:api); await controller.recover(); api.emit('one',ride('one',version:2)); await Future<void>.delayed(Duration.zero); expect(controller.ride?.version,3); controller.dispose(); });
  test('passenger cancel retry aynı id, başarı sonrası yeni logical id kullanır', () async { var n=0; final api=Api(); api.passenger=ride('one'); api.cancelFailures=1; final controller=PassengerRideController(gateway:api,repository:api,requestIdGenerator:()=> 'id-${++n}'); await controller.recover(); await controller.cancel(); await controller.cancel(); expect(api.cancelIds,['id-1','id-1']); api.passenger=ride('two'); await controller.recover(); await controller.cancel(); expect(api.cancelIds.last,'id-2'); controller.dispose(); });
  test('driver retry aynı id ve sonraki transition yeni id kullanır', () async { var n=0; final api=Api(); api.driver=ride('one',status:RideStatus.driverEnRoute); api.arriveFailures=1; final controller=DriverRideController(gateway:api,repository:api,requestIdGenerator:()=> 'id-${++n}'); await controller.recover(); await controller.act(DriverRideAction.arrive); await controller.act(DriverRideAction.arrive); expect(api.arriveIds,['id-1','id-1']); api.emit('one',ride('one',version:2,status:RideStatus.driverArrived)); await Future<void>.delayed(Duration.zero); await controller.act(DriverRideAction.start); expect(api.startIds,['id-2']); controller.dispose(); });
  test('driver stale transition mutationı yeni version ile otomatik tekrarlamaz', () async { final api=Api(); api.driver=ride('one',status:RideStatus.driverEnRoute); api.arriveError=const RideGatewayException('failed-precondition',reason:'stale_ride_version'); api.getValue=ride('one',version:2,status:RideStatus.driverArrived); final controller=DriverRideController(gateway:api,repository:api); await controller.recover(); await controller.act(DriverRideAction.arrive); expect(api.arriveIds.length,1); expect(controller.ride?.version,2); controller.dispose(); });
}

const point=RideLocation(latitude:41,longitude:29,addressLabel:'Adres');
CanonicalRide ride(String id,{int version=1,RideStatus status=RideStatus.matching})=>CanonicalRide(rideId:id,status:status,version:version,pickup:point,dropoff:point,route:const RideRoute(distanceMeters:1,durationSeconds:1,encodedPolyline:'x'));
class Api implements RideGateway,RideStreamRepository {
  CanonicalRide? passenger,driver,getValue; int cancelFailures=0,arriveFailures=0; RideGatewayException? arriveError; final createIds=<String>[],cancelIds=<String>[],arriveIds=<String>[],startIds=<String>[]; final streams=<String,StreamController<CanonicalRide>>{}; final cancelledIds=<String>{};
  StreamController<CanonicalRide> channel(String id)=>streams.putIfAbsent(id,()=>StreamController<CanonicalRide>.broadcast(onCancel:()=>cancelledIds.add(id)));
  bool cancelled(String id)=>cancelledIds.contains(id); void emit(String id,CanonicalRide value)=>channel(id).add(value);
  @override Future<CanonicalRide?> getMyActiveRide()async=>passenger; @override Future<CanonicalRide?> getMyActiveDriverRide()async=>driver;
  @override Future<CanonicalRide> createRide({required String requestId,required RideLocation pickup,required RideLocation dropoff})async{createIds.add(requestId);return ride('created');}
  @override Future<void> cancel({required String rideId,required String requestId,required int expectedVersion,required bool driver})async{cancelIds.add(requestId);if(cancelFailures-->0)throw const RideGatewayException('unavailable');}
  @override Future<void> markDriverArrived({required String rideId,required String requestId,required int expectedVersion})async{arriveIds.add(requestId);if(arriveError case final e?)throw e;if(arriveFailures-->0)throw const RideGatewayException('unavailable');}
  @override Future<void> startRide({required String rideId,required String requestId,required int expectedVersion})async{startIds.add(requestId);}
  @override Future<void> completeRide({required String rideId,required String requestId,required int expectedVersion})async{}
  @override Stream<CanonicalRide> watchRide(String rideId)=>channel(rideId).stream; @override Future<CanonicalRide> getRide(String rideId)async=>getValue??ride(rideId);
}
